### ISSUE TITLE
Error since update Homebridge 1.0.0 / 1.0.1

### ISSUE THREAD

**Issue by phis5533** [DaGolle/homebridge-rfxtrx#3]
Hi, 
since Homebridge update I've got that error :
```
Error: Cannot update reachability on non-bridged accessory!
    at Accessory._this.updateReachability (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:399:13)
    at PlatformAccessory.updateReachability (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:124:34)
    at RFXtrxPlatform.configureAccessory (/usr/local/lib/node_modules/homebridge-rfxtrx/lib/RFXtrxPlatform.js:84:13)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:284:28
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:268:69)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:156:10)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:74:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
```
If you have time to look... 
Thanks
BR

**Comment by phis5533** [comment]
Hello again !

I've found in other project a workaround which does work : 
In the file 
`/usr/local/lib/node_modules/homebridge-rfxtrx/lib/RFXtrxPlatform.js`
put in comment the line 
`//  accessory.updateReachability(true);`

Hope it will be good for everyone
Thank you

**Comment by DaGolle** [comment]
Hi,

Thanks for the feedback!
I'm not actively maintaining this for a while now (as I'm using Home Assistant) and was even thinking of archiving my HomeBridge developments.
However, since some people are still using this, I'm open to suggestions (pull requests, fork...). Let me know if you're interested.

Cheers,
David

**Comment by phis5533** [comment]
Hi David,

Unfortunately I don’t have skills like yours!
But thanks for the proposition and for your work.

By the way, this issue is fixed with the last homebridge version.

Good luck !
