### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by matthieulrg** [DaGolle/homebridge-rfxtrx#5]
Hi, I'm having this issue which is crashing homebridge. Don't know what to do, config file seems okay (see below).

Thank you in advance

**Error**
```
TypeError: Cannot read property 'toLowerCase' of undefined
    at RFXtrxPlatform.getTransmitter (/usr/local/lib/node_modules/homebridge-rfxtrx/lib/RFXtrxPlatform.js:89:52)
    at new Outlet (/usr/local/lib/node_modules/homebridge-rfxtrx/lib/Outlet.js:9:36)
    at RFXtrxPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-rfxtrx/lib/RFXtrxPlatform.js:25:47)
    at Array.forEach (<anonymous>)
    at new RFXtrxPlatform (/usr/local/lib/node_modules/homebridge-rfxtrx/lib/RFXtrxPlatform.js:24:23)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:397:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
```

**Config file**
```
       {
            "platform": "RFXtrx",
            "name": "RFXtrx433E",
            "manufacturer": "RFXCOM",
            "model": "RFXtrx433E USB 433MHz Transceiver",
            "serialNumber": "12345",
            "usbPort": "/dev/ttyUSB0",
            "windowCoverings": [
                {
                    "name": "Volet chambre",
                    "manufacturer": "ASP",
                    "model": "ASP",
                    "serialNumber": "rfxcurtain1",
                    "type": "Blinds1",
                    "subtype": "BLINDS_T3",
                    "deviceID": "0x003537",
                    "orientation": "horizontal",
                    "duration": 400
                },
                {
                    "name": "Volet mezzanine",
                    "manufacturer": "AOK",
                    "model": "AOK",
                    "serialNumber": "rfxcurtain2",
                    "type": "Blinds1",
                    "subtype": "BLINDS_T11",
                    "deviceID": "0x04A6E8",
                    "orientation": "horizontal",
                    "duration": 400
                }
            ],
            "outlets": [
                {}
            ]
        },
```

**Comment by DaGolle** [comment]
Hi, I believe this is caused by the empty "outlets" in your config.
